.TH "THREAD_ARG" 1 "Sun Jan 3 2016" "likana" \" -*- nroff -*-
.ad l
.nh
.SH NAME
THREAD_ARG \- 
.PP
スレッドパラメータ定義  

.SH SYNOPSIS
.br
.PP
.SS "変数"

.in +1c
.ti -1c
.RI "char * \fBdevice\fP"
.br
.RI "\fIcharacter device pointer \fP"
.in -1c
.SH "説明"
.PP 
スレッドパラメータ定義 

.SH "作者"
.PP 
likanaのソースから Doxygen により生成しました。
